name: gg_typedefs
description: This package provides a bunch of typedefs used in various of our projects.
version: 1.1.5
repository: https://github.com/inlavigo/gg_typedefs

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  args: ^2.4.2
  gg_capture_print: ^1.0.2
  lints: ^6.0.0
  test: ^1.16.0
