name: gg_typedefs
description: This package provides a bunch of typedefs used in various of our projects.
version: 1.1.0
homepage: https://github.com/inlavigo/gg_typedefs

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  args: ^2.4.2
  gg_capture_print: ^1.0.2
  gg_install_gg: ^1.0.1
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.16.0
